### ISSUE TITLE
Criar pré visualizador de HTML

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#176]
O Packtools deverá oferecer, como um pacote opcional, a instalação de uma aplicação web com duas funcionalidades principais: validação dos documentos XML e pré-visualização do HTML gerado.

Este desenvolvimento está sendo realizado no branch https://github.com/scieloorg/packtools/tree/viewer, e ainda depende das seguintes atividades:

* [x] Remover dependência da lib *Flask-Script* #187
* [x] Criar lista de dependências concretas para a implantação da webapp #188
* [x] Dockerfile multiestágios para impedir código fonte na implantação #189
* [x] Editor que exibe o XML anotado com os erros de validação não é exibido corretamente #191

**Comment by RPostalli** [comment]
Criado Previewer SciELO - wishlist pela unidade de produção:
https://docs.google.com/spreadsheets/d/1CZvolJOMTwpCK735CfprykOGI0CEQq-uxTV3HqFehHU/edit#gid=0

**Comment by gustavofonseca** [comment]
Os desenvolvimentos foram incorporados no branch master e o pacote está disponível como um *release candidate* para a versão 2.5.

**Comment by gustavofonseca** [comment]
Vou fechar este ticket por considerar que os desenvolvimentos foram concluídos. Melhorias e ajustes deverão ser reportados em novos tickets. Trataremos da implantação do serviço na internet fora do issue tracker do GitHub.
