### ISSUE TITLE
Implementar as regras da versão sps-1.4

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#80]
- [x] [Considerar diferentes protocolos para @xlink:href em ``<ext-link>``](https://github.com/scieloorg/scielo_publishing_schema/issues/185)
- [x] [Considerar ``<permissions>`` em ``<body>`` para licença de objetos no corpo do texto](https://github.com/scieloorg/scielo_publishing_schema/issues/181)
- [x] [Documentar e validar estrutura de copyright](https://github.com/scieloorg/scielo_publishing_schema/issues/180)
- [x] [~~Sugestão de como tratar *counts/@page-count*, *fpage* e *lpage* diferentes em <sub-article>~~](https://github.com/scieloorg/scielo_publishing_schema/issues/179)
- [x] [Documentação da identificação do ID ORCID dos contribuidores](https://github.com/scieloorg/scielo_publishing_schema/issues/174)
- [x] [Elemento ``<fn-group>`` pode ocorrer zero ou mais vezes](https://github.com/scieloorg/scielo_publishing_schema/issues/169)
- [x] [<app> pode ocorrer zero ou mais vezes em ``<app-group>``](https://github.com/scieloorg/scielo_publishing_schema/issues/168)
- [x] [*related-article* deve permitir outros tipos de *ext-link-type*](https://github.com/scieloorg/scielo_publishing_schema/issues/166)
- [x] [Acrescentar possibilidade de título ``<title>`` em ``<fn-group>``](https://github.com/scieloorg/scielo_publishing_schema/issues/128)
- [x] [Acrescentar na tag ``<issue>`` possibilidade de número especial](https://github.com/scieloorg/scielo_publishing_schema/issues/119)
- [x] [Avaliar *license/license-p* no idioma do artigo ou *en*](https://github.com/scieloorg/scielo_publishing_schema/issues/71)
- [x] [Incoerência em obrigatoriedade de @id em ``<app>`` e ``<supplementary-material>``](https://github.com/scieloorg/scielo_publishing_schema/issues/66)

Listagem derivada da disponível em https://github.com/scieloorg/scielo_publishing_schema/issues?q=is%3Aissue+milestone%3A%22vers%C3%A3o+1.4%22+is%3Aclosed
